# DigitalOcean App Platform - Minimal Working Configuration
# This is a simplified version that should deploy successfully
# Deploy this first, then add features incrementally

name: seahorse-app
region: nyc

# Main API Service
services:
  - name: api
    # GitHub source
    github:
      repo: kasing213/Quant-analysis
      branch: master
      deploy_on_push: true

    # Build from Dockerfile
    dockerfile_path: Dockerfile

    # Start with smallest instance to minimize costs during testing
    instance_size_slug: basic-xxs  # $12/month (512MB RAM, 1 vCPU)
    instance_count: 1

    http_port: 8000

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 90  # Increased to 90s to allow for dependency installation
      period_seconds: 15
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 4

    # Routes
    routes:
      - path: /

    # MINIMAL Environment variables - No secrets for initial deployment
    envs:
      # Application settings
      - key: API_HOST
        value: "0.0.0.0"
        scope: RUN_TIME

      - key: API_PORT
        value: "8000"
        scope: RUN_TIME

      - key: ENVIRONMENT
        value: "production"
        scope: RUN_TIME

      - key: LOG_LEVEL
        value: "INFO"
        scope: RUN_TIME

      # Disable features that require external services
      - key: BINANCE_ENABLE_BOTS
        value: "false"
        scope: RUN_TIME

      - key: BINANCE_ENABLE_MARKET_DATA
        value: "false"  # Disable until we add API keys
        scope: RUN_TIME

      - key: ENABLE_DASHBOARD_FIXTURES
        value: "true"  # Use mock data for now
        scope: RUN_TIME

      # Use test mode without real API keys
      - key: BINANCE_TESTNET
        value: "true"
        scope: RUN_TIME

      - key: BINANCE_TEST_MODE
        value: "true"
        scope: RUN_TIME

      # Trading pairs (for when we enable market data)
      - key: TRADING_PAIRS
        value: "BTCUSDT,ETHUSDT,BNBUSDT"
        scope: RUN_TIME

      # SUPABASE DATABASE CONNECTION
      # NOTE: Set these values in DigitalOcean App Platform Console:
      # Settings → Environment Variables → Add Variable → Mark as "Secret"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        # Value format: postgresql://[user]:[password]@[host]:[port]/[database]?pgbouncer=true&connection_limit=1

      - key: POSTGRES_HOST
        scope: RUN_TIME
        # Value: Your Supabase host (e.g., db.xxxxx.supabase.co)

      - key: POSTGRES_PORT
        value: "5432"
        scope: RUN_TIME

      - key: POSTGRES_DB
        value: "postgres"
        scope: RUN_TIME

      - key: POSTGRES_USER
        scope: RUN_TIME
        # Value: Your Supabase username (e.g., postgres.xxxxx)

      - key: POSTGRES_PASSWORD
        scope: RUN_TIME
        type: SECRET
        # Value: Your Supabase database password

      # Binance API Keys (from testnet)
      # NOTE: Set these values in DigitalOcean App Platform Console
      - key: BINANCE_API_KEY
        scope: RUN_TIME
        type: SECRET
        # Value: Your Binance Testnet API Key

      - key: BINANCE_API_SECRET
        scope: RUN_TIME
        type: SECRET
        # Value: Your Binance Testnet API Secret

# NOTE: Redis removed for initial deployment - can add later if needed
